name = "cloud-worker"
main = "worker/src/worker.js"
compatibility_date = "2025-03-23"
workers_dev = true
route = "plc-web.online/*"

[[kv_namespaces]]
binding = "USERS"
id = "53b5cca7e0e34c34978581f25ed8d010"

[assets]
directory = "public"

