name = "cloud-worker"
main = "worker/src/worker.js"
compatibility_date = "2025-03-23"

[[assets]]
binding = "ASSETS"
path = "public"

[[kv_namespaces]]
binding = "USERS"
id = "a4a892b79a7f4c39ae316269ed919e6e"
