name = "cloud-worker"
main = "src/worker.js"
compatibility_date = "2025-03-23"
workers_dev = true
preview_urls = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "USERS"
id = "a4a892b79a7f4c39ae316269ed919e6e"
